# Generated by Django 5.0.1 on 2024-01-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
    ]
